previews:
  generation: automatic
services:
  - type: web
    name: nestjs-server
    runtime: node
    plan: standard
    buildCommand: yarn install && yarn build
    startCommand: yarn start:prod
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables as needed
    # Optionally, set up health checks
    healthCheckPath: /health

databases:
  - name: my_test_db
    plan: pro-4gb
    previewPlan: basic-1gb
    previewDiskSizeGB: 5
